name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# permissions:
#   contents: write  # permissão para criar releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip

    - name: Rodar testes
      run: |
        python -m unittest discover

    - name: Gerar versão semântica
      id: version
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: "Release v${{ github.run_number }}"